package org.example.Server.Entities.TCP;

public enum RequestType {
    REGISTER,
    LOGIN,
    LOGOUT,
    MENU_USER,
    GET_STUDENTS,
    GET_SCHOLARSHIPS,
    GET_MY_PROFILE,
    GET_MY_PROFILE_ACCOUNTANT,
    GET_MY_PROFILE_ADMIN,
    GET_MY_SESSION,
    GET_SCHOLARSHIP_AMOUNT,
    GET_MY_SCHOLARSHIP,
    UPDATE_SCHOLARSHIP,
    GET_GROUPS,
    ADD_STUDENT,
    DELETE_STUDENT,
    ADD_SESSION,
    GET_MY_SUBJECTS,
    ADD_GROUP,
    DELETE_GROUP,
}
